@startuml
'https://plantuml.com/class-diagram

' reference
' https://plantuml.com/class-diagram

interface IMiFareCard

IMiFareCard <|- MiFareCard
MiFareCard <|-- VipaImpl : < processes

skinparam class {
    BackgroundColor PaleGreen
    ArrowColor SeaGreen
    'BorderColor Red
    BackgroundColor<<Foo>> Wheat
    BorderColor<<Foo>> Tomato
}

class MiFareCard {
    -Dictionary<int index,byte[] data> fileData
    +GetFileData()
}

class VipaImpl <<Foo>> {
    -Object [MiFareImpl]
    +GetCardData()
    -Authenticate()
    -ContinueContactlessTransaction()
}

enum CardStatus {
    AUTHENTICATED
    VSS_SCRIPTS_MISSING
}

enum FileTypes {
    ENVIRONMENT_HOLDER
    STANDARD_DATA
}

enum TransportApplicationKeys {
    MASTER_KEY_0
    WORK_KEY_1
    WORK_KEY_2
    WORK_KEY_3
    WORK_KEY_4
}
@enduml