@startuml
'https://plantuml.com/class-diagram

' reference
' https://plantuml.com/class-diagram

interface IMiFare
interface IMiFareCard

MiFareImpl o-- MiFareCard : aggregation
IMiFareCard <|- MiFareCard
IMiFare <|- MiFareImpl
MiFareImpl <|-- VipaImpl

skinparam class {
    BackgroundColor PaleGreen
    ArrowColor SeaGreen
    'BorderColor Red
    BackgroundColor<<Foo>> Wheat
    BorderColor<<Foo>> Tomato
}

class MiFareCard {
    -Dictionary<int index,byte[] data> fileData
    +GetFileData()
}

abstract class MiFareImpl {
    -Object MiFareCard
}

class VipaImpl <<Foo>> {
    -Object [MiFareImpl]
    +GetCardData()
    -Authenticate()
    -ContinueContactlessTransaction()
}

enum CardStatus {
AUTHENTICATED
VSS_SCRIPTS_MISSING
}

@enduml